### ISSUE TITLE
Code update in Exploratory analysis of RNAseq count data

### ISSUE THREAD

**Issue by mvanrongen** [tavareshugo/2019-07-01-bioinformatics_for_biologists#1]
In the section **Joining tables together**, the following code could be altered:

`trans_cts_long <- full_join(trans_cts_long, sample_info, by = ("sample"))` to `trans_cts_long <- full_join(trans_cts_long, sample_info, by = "sample")` to make it more consistent with the code further down.

**Comment by tavareshugo** [comment]
and super thanks! :)
