### ISSUE TITLE
Dead link in Visualising samples on PC space

### ISSUE THREAD

**Issue by mvanrongen** [tavareshugo/2019-07-01-bioinformatics_for_biologists#2]
"We talk more about standardizing gene expression data in the gene clustering lesson."

The link to `gene clustering lesson` is incorrect (it links to `/data-carpentry-rnaseq/05_rnaseq_clustering.html` and should probably be `/data-carpentry-rnaseq/04b_rnaseq_clustering.html`).

**Comment by tavareshugo** [comment]
More thanks!
